services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: blockchain
      MYSQL_USER: root
      MYSQL_PASSWORD: Sumanth@1990
    ports:
      - "3366:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
